/*Each new term in the Fibonacci sequence is generated by adding the*/
/*previous two terms. By starting with 1 and 2, the first 10 terms will be:*/
/*1, 2, 3, 5, 8, 13, 21, 34, 55, 89.*/
/*By considering the terms in the Fibonacci sequence whose values*/
/*do not exceed 4,000,000, write a program that finds and prints the sum of*/
/*the even-valued terms, followed by a new line.*/
/*You are allowed to use the standard library*/

#include <stdio.h>

/**
 * main - task
 * Return: 0
 */
int main(void)
{
	long sum = 0, a = 0, swap = 0, fib = 1;

	while (fib <= 4000000)
	{
		a = swap;
		swap = fib;
		fib = a + swap;
		if (fib % 2 == 0)
			sum += fib;
	}
	printf("%lu\n", sum);
	return (0);
}
